# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'gpro' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'AWSCore'
  pod 'AWSCognitoIdentityProvider'
  
  pod 'APIKit', '~> 2.0'
  pod 'Himotoki', '~> 2.1.1'

  target 'gproTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'gproUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
